services:
  - type: web
    name: kupi-bot
    runtime: node
    rootDir: apps/bot
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
